# -*- coding: utf-8 -*-
"""
/***************************************************************************
 geogrid
                                 A QGIS plugin
 Plugin build geographic grid, frame borders and labels
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-09-06
        copyright            : (C) 2018 by Konstantin Puzankov
        email                : konst555@mail.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load geogrid class from file geogrid.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geogrid import geogrid
    return geogrid(iface)
