# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geo_grid_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_geogridDialogBase(object):
    def setupUi(self, geogridDialogBase):
        geogridDialogBase.setObjectName("geogridDialogBase")
        geogridDialogBase.resize(451, 567)
        geogridDialogBase.setMinimumSize(QtCore.QSize(420, 567))
        geogridDialogBase.setWindowTitle("Geo Grid")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/geogrid/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        geogridDialogBase.setWindowIcon(icon)
        geogridDialogBase.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(geogridDialogBase)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(geogridDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(402, 180))
        self.frame.setAutoFillBackground(False)
        self.frame.setInputMethodHints(QtCore.Qt.ImhNone)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.lat_min_d = QtWidgets.QLineEdit(self.frame)
        self.lat_min_d.setGeometry(QtCore.QRect(70, 125, 61, 19))
        self.lat_min_d.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lat_min_d.setInputMask("")
        self.lat_min_d.setPlaceholderText("")
        self.lat_min_d.setObjectName("lat_min_d")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(9, 125, 51, 16))
        self.label.setObjectName("label")
        self.lat_min_m = QtWidgets.QLineEdit(self.frame)
        self.lat_min_m.setGeometry(QtCore.QRect(134, 125, 81, 20))
        self.lat_min_m.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lat_min_m.setInputMask("")
        self.lat_min_m.setPlaceholderText("")
        self.lat_min_m.setObjectName("lat_min_m")
        self.lat_max_d = QtWidgets.QLineEdit(self.frame)
        self.lat_max_d.setGeometry(QtCore.QRect(220, 125, 61, 20))
        self.lat_max_d.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lat_max_d.setInputMask("")
        self.lat_max_d.setPlaceholderText("")
        self.lat_max_d.setObjectName("lat_max_d")
        self.lat_max_m = QtWidgets.QLineEdit(self.frame)
        self.lat_max_m.setGeometry(QtCore.QRect(286, 125, 91, 20))
        self.lat_max_m.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lat_max_m.setInputMask("")
        self.lat_max_m.setPlaceholderText("")
        self.lat_max_m.setObjectName("lat_max_m")
        self.lon_min_m = QtWidgets.QLineEdit(self.frame)
        self.lon_min_m.setGeometry(QtCore.QRect(134, 150, 81, 20))
        self.lon_min_m.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lon_min_m.setInputMask("")
        self.lon_min_m.setPlaceholderText("")
        self.lon_min_m.setObjectName("lon_min_m")
        self.lon_min_d = QtWidgets.QLineEdit(self.frame)
        self.lon_min_d.setGeometry(QtCore.QRect(70, 150, 61, 19))
        self.lon_min_d.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lon_min_d.setInputMask("")
        self.lon_min_d.setPlaceholderText("")
        self.lon_min_d.setObjectName("lon_min_d")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(9, 150, 51, 16))
        self.label_2.setObjectName("label_2")
        self.lon_max_d = QtWidgets.QLineEdit(self.frame)
        self.lon_max_d.setGeometry(QtCore.QRect(221, 150, 61, 19))
        self.lon_max_d.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lon_max_d.setInputMask("")
        self.lon_max_d.setPlaceholderText("")
        self.lon_max_d.setObjectName("lon_max_d")
        self.lon_max_m = QtWidgets.QLineEdit(self.frame)
        self.lon_max_m.setGeometry(QtCore.QRect(286, 150, 91, 20))
        self.lon_max_m.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lon_max_m.setInputMask("")
        self.lon_max_m.setPlaceholderText("")
        self.lon_max_m.setObjectName("lon_max_m")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(100, 80, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(230, 80, 121, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(90, 100, 121, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(230, 100, 151, 20))
        self.label_6.setObjectName("label_6")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.btn_copy_minmax = QtWidgets.QPushButton(self.frame)
        self.btn_copy_minmax.setGeometry(QtCore.QRect(220, 40, 161, 31))
        self.btn_copy_minmax.setObjectName("btn_copy_minmax")
        self.mMapLayerComboBox = QgsMapLayerComboBox(self.frame)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(10, 40, 201, 31))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(geogridDialogBase)
        self.frame_2.setMinimumSize(QtCore.QSize(402, 110))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(3)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.lat_step_d = QtWidgets.QLineEdit(self.frame_2)
        self.lat_step_d.setGeometry(QtCore.QRect(100, 50, 51, 20))
        self.lat_step_d.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.lat_step_d.setInputMask("")
        self.lat_step_d.setPlaceholderText("")
        self.lat_step_d.setObjectName("lat_step_d")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(30, 50, 51, 16))
        self.label_7.setObjectName("label_7")
        self.lat_step_m = QtWidgets.QLineEdit(self.frame_2)
        self.lat_step_m.setGeometry(QtCore.QRect(180, 50, 51, 20))
        self.lat_step_m.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.lat_step_m.setInputMask("")
        self.lat_step_m.setPlaceholderText("")
        self.lat_step_m.setObjectName("lat_step_m")
        self.lon_step_m = QtWidgets.QLineEdit(self.frame_2)
        self.lon_step_m.setGeometry(QtCore.QRect(180, 80, 51, 20))
        self.lon_step_m.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.lon_step_m.setInputMask("")
        self.lon_step_m.setPlaceholderText("")
        self.lon_step_m.setObjectName("lon_step_m")
        self.lon_step_d = QtWidgets.QLineEdit(self.frame_2)
        self.lon_step_d.setGeometry(QtCore.QRect(100, 80, 51, 20))
        self.lon_step_d.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.lon_step_d.setInputMask("")
        self.lon_step_d.setPlaceholderText("")
        self.lon_step_d.setObjectName("lon_step_d")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(30, 80, 51, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(100, 10, 121, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(250, 30, 171, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(100, 30, 121, 20))
        self.label_11.setObjectName("label_11")
        self.spin_n_subgrd = QtWidgets.QSpinBox(self.frame_2)
        self.spin_n_subgrd.setGeometry(QtCore.QRect(300, 60, 41, 31))
        self.spin_n_subgrd.setMinimum(1)
        self.spin_n_subgrd.setMaximum(20)
        self.spin_n_subgrd.setProperty("value", 1)
        self.spin_n_subgrd.setObjectName("spin_n_subgrd")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(geogridDialogBase)
        self.frame_3.setMinimumSize(QtCore.QSize(402, 110))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(3)
        self.frame_3.setObjectName("frame_3")
        self.combo_n_brdminuts = QtWidgets.QComboBox(self.frame_3)
        self.combo_n_brdminuts.setGeometry(QtCore.QRect(350, 10, 69, 22))
        self.combo_n_brdminuts.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.combo_n_brdminuts.setObjectName("combo_n_brdminuts")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.combo_n_brdminuts.addItem("")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(90, 10, 191, 20))
        self.label_12.setObjectName("label_12")
        self.combo_n_brdtiks = QtWidgets.QComboBox(self.frame_3)
        self.combo_n_brdtiks.setGeometry(QtCore.QRect(350, 40, 69, 22))
        self.combo_n_brdtiks.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.combo_n_brdtiks.setObjectName("combo_n_brdtiks")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.combo_n_brdtiks.addItem("")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(90, 40, 171, 16))
        self.label_13.setObjectName("label_13")
        self.combo_n_lblminuts = QtWidgets.QComboBox(self.frame_3)
        self.combo_n_lblminuts.setGeometry(QtCore.QRect(350, 70, 69, 22))
        self.combo_n_lblminuts.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.combo_n_lblminuts.setObjectName("combo_n_lblminuts")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.combo_n_lblminuts.addItem("")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(90, 70, 251, 20))
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.frame_3)
        self.Save_btn = QtWidgets.QToolButton(geogridDialogBase)
        self.Save_btn.setMinimumSize(QtCore.QSize(120, 25))
        self.Save_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.Save_btn.setObjectName("Save_btn")
        self.verticalLayout.addWidget(self.Save_btn)
        self.Fname_lineEdit = QtWidgets.QLineEdit(geogridDialogBase)
        self.Fname_lineEdit.setObjectName("Fname_lineEdit")
        self.verticalLayout.addWidget(self.Fname_lineEdit)
        self.add_layers = QtWidgets.QCheckBox(geogridDialogBase)
        self.add_layers.setChecked(True)
        self.add_layers.setObjectName("add_layers")
        self.verticalLayout.addWidget(self.add_layers)
        self.button_box = QtWidgets.QDialogButtonBox(geogridDialogBase)
        self.button_box.setToolTip("")
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(geogridDialogBase)
        self.combo_n_lblminuts.setCurrentIndex(0)
        self.button_box.accepted.connect(geogridDialogBase.accept)
        self.button_box.rejected.connect(geogridDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(geogridDialogBase)
        geogridDialogBase.setTabOrder(self.mMapLayerComboBox, self.btn_copy_minmax)
        geogridDialogBase.setTabOrder(self.btn_copy_minmax, self.lat_min_d)
        geogridDialogBase.setTabOrder(self.lat_min_d, self.lat_min_m)
        geogridDialogBase.setTabOrder(self.lat_min_m, self.lat_max_d)
        geogridDialogBase.setTabOrder(self.lat_max_d, self.lat_max_m)
        geogridDialogBase.setTabOrder(self.lat_max_m, self.lon_min_d)
        geogridDialogBase.setTabOrder(self.lon_min_d, self.lon_min_m)
        geogridDialogBase.setTabOrder(self.lon_min_m, self.lon_max_d)
        geogridDialogBase.setTabOrder(self.lon_max_d, self.lon_max_m)
        geogridDialogBase.setTabOrder(self.lon_max_m, self.lat_step_d)
        geogridDialogBase.setTabOrder(self.lat_step_d, self.lat_step_m)
        geogridDialogBase.setTabOrder(self.lat_step_m, self.lon_step_d)
        geogridDialogBase.setTabOrder(self.lon_step_d, self.lon_step_m)
        geogridDialogBase.setTabOrder(self.lon_step_m, self.spin_n_subgrd)
        geogridDialogBase.setTabOrder(self.spin_n_subgrd, self.combo_n_brdminuts)
        geogridDialogBase.setTabOrder(self.combo_n_brdminuts, self.combo_n_brdtiks)
        geogridDialogBase.setTabOrder(self.combo_n_brdtiks, self.combo_n_lblminuts)
        geogridDialogBase.setTabOrder(self.combo_n_lblminuts, self.Save_btn)
        geogridDialogBase.setTabOrder(self.Save_btn, self.Fname_lineEdit)
        geogridDialogBase.setTabOrder(self.Fname_lineEdit, self.add_layers)

    def retranslateUi(self, geogridDialogBase):
        _translate = QtCore.QCoreApplication.translate
        self.lat_min_d.setText(_translate("geogridDialogBase", "-10"))
        self.label.setText(_translate("geogridDialogBase", "Latitude"))
        self.lat_min_m.setText(_translate("geogridDialogBase", "0"))
        self.lat_max_d.setText(_translate("geogridDialogBase", "10"))
        self.lat_max_m.setText(_translate("geogridDialogBase", "0"))
        self.lon_min_m.setText(_translate("geogridDialogBase", "0"))
        self.lon_min_d.setText(_translate("geogridDialogBase", "-10"))
        self.label_2.setText(_translate("geogridDialogBase", "Longitude"))
        self.lon_max_d.setText(_translate("geogridDialogBase", "10"))
        self.lon_max_m.setText(_translate("geogridDialogBase", "0"))
        self.label_3.setText(_translate("geogridDialogBase", "Minimum"))
        self.label_4.setText(_translate("geogridDialogBase", "Maximum"))
        self.label_5.setText(_translate("geogridDialogBase", "degrees minutes"))
        self.label_6.setText(_translate("geogridDialogBase", "degrees minutes"))
        self.label_16.setText(_translate("geogridDialogBase", "COVERAGE"))
        self.btn_copy_minmax.setText(_translate("geogridDialogBase", "Copy coverage"))
        self.lat_step_d.setText(_translate("geogridDialogBase", "1"))
        self.label_7.setText(_translate("geogridDialogBase", "Latitude"))
        self.lat_step_m.setText(_translate("geogridDialogBase", "0"))
        self.lon_step_m.setText(_translate("geogridDialogBase", "0"))
        self.lon_step_d.setText(_translate("geogridDialogBase", "1"))
        self.label_8.setText(_translate("geogridDialogBase", "Longitude"))
        self.label_9.setText(_translate("geogridDialogBase", "Step grid space"))
        self.label_10.setText(_translate("geogridDialogBase", "gridlines divided into parts"))
        self.label_11.setText(_translate("geogridDialogBase", "degrees minutes"))
        self.label_15.setText(_translate("geogridDialogBase", "GRID"))
        self.combo_n_brdminuts.setItemText(0, _translate("geogridDialogBase", "1"))
        self.combo_n_brdminuts.setItemText(1, _translate("geogridDialogBase", "2"))
        self.combo_n_brdminuts.setItemText(2, _translate("geogridDialogBase", "3"))
        self.combo_n_brdminuts.setItemText(3, _translate("geogridDialogBase", "4"))
        self.combo_n_brdminuts.setItemText(4, _translate("geogridDialogBase", "5"))
        self.combo_n_brdminuts.setItemText(5, _translate("geogridDialogBase", "6"))
        self.combo_n_brdminuts.setItemText(6, _translate("geogridDialogBase", "10"))
        self.combo_n_brdminuts.setItemText(7, _translate("geogridDialogBase", "15"))
        self.combo_n_brdminuts.setItemText(8, _translate("geogridDialogBase", "20"))
        self.combo_n_brdminuts.setItemText(9, _translate("geogridDialogBase", "30"))
        self.combo_n_brdminuts.setItemText(10, _translate("geogridDialogBase", "60"))
        self.combo_n_brdminuts.setItemText(11, _translate("geogridDialogBase", "120"))
        self.combo_n_brdminuts.setItemText(12, _translate("geogridDialogBase", "180"))
        self.combo_n_brdminuts.setItemText(13, _translate("geogridDialogBase", "240"))
        self.combo_n_brdminuts.setItemText(14, _translate("geogridDialogBase", "300"))
        self.combo_n_brdminuts.setItemText(15, _translate("geogridDialogBase", "600"))
        self.label_12.setText(_translate("geogridDialogBase", "Border dividing Step (minutes)"))
        self.combo_n_brdtiks.setItemText(0, _translate("geogridDialogBase", "1"))
        self.combo_n_brdtiks.setItemText(1, _translate("geogridDialogBase", "2"))
        self.combo_n_brdtiks.setItemText(2, _translate("geogridDialogBase", "3"))
        self.combo_n_brdtiks.setItemText(3, _translate("geogridDialogBase", "5"))
        self.combo_n_brdtiks.setItemText(4, _translate("geogridDialogBase", "6"))
        self.combo_n_brdtiks.setItemText(5, _translate("geogridDialogBase", "10"))
        self.combo_n_brdtiks.setItemText(6, _translate("geogridDialogBase", "20"))
        self.combo_n_brdtiks.setItemText(7, _translate("geogridDialogBase", "30"))
        self.combo_n_brdtiks.setItemText(8, _translate("geogridDialogBase", "60"))
        self.combo_n_brdtiks.setItemText(9, _translate("geogridDialogBase", "120"))
        self.combo_n_brdtiks.setItemText(10, _translate("geogridDialogBase", "180"))
        self.combo_n_brdtiks.setItemText(11, _translate("geogridDialogBase", "240"))
        self.combo_n_brdtiks.setItemText(12, _translate("geogridDialogBase", "300"))
        self.combo_n_brdtiks.setItemText(13, _translate("geogridDialogBase", "600"))
        self.label_13.setText(_translate("geogridDialogBase", "Step border Ticks (minutes )"))
        self.combo_n_lblminuts.setItemText(0, _translate("geogridDialogBase", "1"))
        self.combo_n_lblminuts.setItemText(1, _translate("geogridDialogBase", "2"))
        self.combo_n_lblminuts.setItemText(2, _translate("geogridDialogBase", "3"))
        self.combo_n_lblminuts.setItemText(3, _translate("geogridDialogBase", "5"))
        self.combo_n_lblminuts.setItemText(4, _translate("geogridDialogBase", "6"))
        self.combo_n_lblminuts.setItemText(5, _translate("geogridDialogBase", "10"))
        self.combo_n_lblminuts.setItemText(6, _translate("geogridDialogBase", "20"))
        self.combo_n_lblminuts.setItemText(7, _translate("geogridDialogBase", "30"))
        self.combo_n_lblminuts.setItemText(8, _translate("geogridDialogBase", "60"))
        self.combo_n_lblminuts.setItemText(9, _translate("geogridDialogBase", "120"))
        self.combo_n_lblminuts.setItemText(10, _translate("geogridDialogBase", "180"))
        self.combo_n_lblminuts.setItemText(11, _translate("geogridDialogBase", "240"))
        self.combo_n_lblminuts.setItemText(12, _translate("geogridDialogBase", "300"))
        self.combo_n_lblminuts.setItemText(13, _translate("geogridDialogBase", "600"))
        self.label_14.setText(_translate("geogridDialogBase", "Step of labels along a border (minute)"))
        self.label_18.setText(_translate("geogridDialogBase", "BORDER"))
        self.Save_btn.setText(_translate("geogridDialogBase", "Save As"))
        self.add_layers.setText(_translate("geogridDialogBase", "Add layers to the current project"))

from qgsmaplayercombobox import QgsMapLayerComboBox
from . import resources
